# Generated by Django 5.0.7 on 2024-07-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='close',
            field=models.TimeField(verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='open',
            field=models.TimeField(verbose_name='Opening Time'),
        ),
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=1000)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.place')),
            ],
        ),
    ]
