# Generated by Django 5.0.7 on 2024-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_hours_close_alter_hours_open_architect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architect',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='architects',
            field=models.ManyToManyField(to='my_app.architect'),
        ),
    ]
